from google.cloud import bigquery

client = bigquery.Client()

table_id = "cloocus-da-solution.dw_cloocus.hellocloocus_bqtable"
bucket_name = "cloocus-taw-retail"

job_config = bigquery.LoadJobConfig(
    schema=[
        bigquery.SchemaField("CUST_ID", "INTEGER"),
        bigquery.SchemaField("PROD_SKID", "INTEGER"),
        bigquery.SchemaField("STORE_SKID", "INTEGER"),
        bigquery.SchemaField("SALES_DATE", "DATE"),
        bigquery.SchemaField("PRMTN_SKID", "INTEGER"),
        bigquery.SchemaField("POS_UNIT_SALES_AMT", "FLOAT"),
        bigquery.SchemaField("POS_VAL_SALES_AMT", "FLOAT"),
        bigquery.SchemaField("POS_COST_AMT", "FLOAT"),
        bigquery.SchemaField("POS_STORE_CNT", "FLOAT"),
        bigquery.SchemaField("SHELF_PRICE_VAL", "FLOAT"),
        bigquery.SchemaField("SHELF_PRICE_WITH_TAX_VAL", "STRING"),
        bigquery.SchemaField("COST_PRICE_VAL", "STRING"),
        bigquery.SchemaField("PRMTD_POS_UNIT_SALES_VAL", "FLOAT"),
        bigquery.SchemaField("PRMTD_POS_VAL_SALES_VAL", "FLOAT"),
        bigquery.SchemaField("PRMTD_POS_COST_VAL", "STRING"),
        bigquery.SchemaField("NON_PRMTD_POS_UNIT_SALES_VAL", "FLOAT"),
        bigquery.SchemaField("NON_PRMTD_POS_VAL_SALES_VAL", "FLOAT"),
        bigquery.SchemaField("NON_PRMTD_POS_COST_VAL", "STRING"),
        bigquery.SchemaField("TRNVR_INCLD_VAT_VAL", "STRING"),
        bigquery.SchemaField("TRNVR_EXCLD_VAT_VAL", "STRING"),
        bigquery.SchemaField("PRMTD_SHELF_PRICE_VAL", "STRING"),
        bigquery.SchemaField("PRMTD_SHELF_PRICE_WITH_TAX_VAL", "STRING"),
        bigquery.SchemaField("POS_VALID_IND", "BOOLEAN"),
        bigquery.SchemaField("STORE_UNITS_ONHND_VAL", "FLOAT"),
        bigquery.SchemaField("STORE_VAL_ONHND_VAL", "FLOAT"),
        bigquery.SchemaField("STORE_UNITS_ON_ORDR_VAL", "FLOAT"),
        bigquery.SchemaField("STORE_UNITS_IN_TRNST_VAL", "FLOAT"),
        bigquery.SchemaField("STORE_UNITS_RETND_VAL", "STRING"),
        bigquery.SchemaField("STORE_UNITS_ON_HOLD_VAL", "STRING"),
        bigquery.SchemaField("STORE_UNITS_WDRWN_VAL", "STRING"),
        bigquery.SchemaField("STORE_UNITS_RCVD_VAL", "STRING"),
        bigquery.SchemaField("SHELF_CPCTY_IN_UNITS_VAL", "FLOAT"),
        bigquery.SchemaField("ALOCD_UNITS_ONHND_IN_WHSE_VAL", "STRING"),
        bigquery.SchemaField("STORE_FORCE_OUT_UNITS_VAL", "STRING"),
        bigquery.SchemaField("CLRNC_POS_UNIT_SALES_VAL", "STRING"),
        bigquery.SchemaField("CLRNC_POS_SALES_VAL", "STRING"),
        bigquery.SchemaField("CLRNC_POS_COST_VAL", "STRING"),
        bigquery.SchemaField("CMPBL_STORE_POS_UNIT_SALES_VAL", "STRING"),
        bigquery.SchemaField("CMPBL_STORE_POS_VAL_SALES_VAL", "STRING"),
        bigquery.SchemaField("CRCLR_POS_UNIT_SALES_VAL", "STRING"),
        bigquery.SchemaField("CRCLR_POS_VAL_SALES_VAL", "STRING"),
        bigquery.SchemaField("TPR_POS_UNIT_SALES_VAL", "STRING"),
        bigquery.SchemaField("TPR_POS_VAL_SALES_VAL", "STRING"),
        bigquery.SchemaField("CUST_IN_STOCK_IND", "BOOLEAN"),
        bigquery.SchemaField("CUST_RPLNT_IN_STOCK_IND", "INTEGER"),
        bigquery.SchemaField("MARK_UP_MARK_DOWN_AMT_VAL", "STRING"),
        bigquery.SchemaField("MARK_UP_MARK_DOWN_QTY_VAL", "STRING"),
        bigquery.SchemaField("MARK_UP_MARK_DOWN_PCT_VAL", "STRING"),
        bigquery.SchemaField("STORE_ONHND_COST_VAL", "FLOAT"),
        bigquery.SchemaField("BCKRM_STORE_UNITS_ONHND_VAL", "STRING"),
        bigquery.SchemaField("STORE_ON_ORDR_VAL", "FLOAT"),
        bigquery.SchemaField("STORE_ON_ORDR_COST_VAL", "FLOAT"),
        bigquery.SchemaField("STORE_IN_TRNST_VAL", "FLOAT"),
        bigquery.SchemaField("STORE_IN_TRNST_COST_VAL", "FLOAT"),
        bigquery.SchemaField("ALOCD_ONHND_IN_WHSE_VAL", "FLOAT"),
        bigquery.SchemaField("ALOCD_ONHND_IN_WHSE_COST_VAL", "FLOAT"),
        bigquery.SchemaField("POS_TRATD_IND", "BOOLEAN"),
        bigquery.SchemaField("CANCL_WHEN_OUT_IND", "BOOLEAN"),
        bigquery.SchemaField("ORDR_BOOK_IND", "BOOLEAN"),
        bigquery.SchemaField("UNIT_PRICE_HISTR_VAL", "STRING"),
        bigquery.SchemaField("OUTER_CASE_QTY_HISTR_VAL", "STRING"),
        bigquery.SchemaField("INNER_CASE_QTY_HISTR_VAL", "STRING"),
        bigquery.SchemaField("ITEM_STTUS_HISTR_VAL", "STRING"),
        bigquery.SchemaField("NEVER_OUT_HISTR_VAL_IND", "STRING"),
        bigquery.SchemaField("DSNLZ_DEMND_UNITS_RATE_VAL", "STRING"),
        bigquery.SchemaField("DSNLZ_DEMND_VAL_RATE_VAL", "STRING"),
        bigquery.SchemaField("TOT_ADJ_RETL_VAL", "STRING"),
        bigquery.SchemaField("TOT_ADJ_QTY_VAL", "STRING"),
        bigquery.SchemaField("ONHND_ADJ_RETL_VAL", "FLOAT"),
        bigquery.SchemaField("ONHND_ADJ_QTY_VAL", "FLOAT"),
        bigquery.SchemaField("BCKRM_ADJ_RETL_VAL", "FLOAT"),
        bigquery.SchemaField("BCKRM_ADJ_QTY_VAL", "FLOAT"),
        bigquery.SchemaField("ORDR_POINT_QTY_VAL", "STRING"),
        bigquery.SchemaField("SFTY_STOCK_QTY_VAL", "STRING"),
        bigquery.SchemaField("SGSTD_ORDR_QTY_VAL", "STRING"),
        bigquery.SchemaField("STORE_VAL_RCVD_VAL", "STRING"),
        bigquery.SchemaField("STORE_COST_RCVD_VAL", "STRING"),
        bigquery.SchemaField("DIRCT_TO_STORE_UNITS_RCVD_VAL", "STRING"),
        bigquery.SchemaField("WHSE_TO_STORE_UNITS_RCVD_VAL", "STRING"),
        bigquery.SchemaField("BSKT_SALES_VAL", "STRING"),
        bigquery.SchemaField("BSKT_OCRNC_VAL", "STRING"),
        bigquery.SchemaField("BSKT_SCAN_CNT", "STRING"),
        bigquery.SchemaField("BSKT_PROFT_VAL", "STRING"),
        bigquery.SchemaField("BSKT_COST_VAL", "STRING"),
        bigquery.SchemaField("SHELF_MIN_QTY_VAL", "STRING"),
        bigquery.SchemaField("RETLR_STORE_OOS_LOST_SALES_VAL", "STRING"),
        bigquery.SchemaField("TRGT_STORE_UNITS_ONHND_VAL", "STRING"),
        bigquery.SchemaField("POS_CASES_SALES_VAL", "STRING"),
        bigquery.SchemaField("PRMTD_POS_CASES_SALES_VAL", "STRING"),
        bigquery.SchemaField("NON_PRMTD_POS_CASES_SALES_VAL", "STRING"),
        bigquery.SchemaField("ALT_ONHND_QTY_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_01_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_02_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_03_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_04_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_05_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_06_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_07_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_08_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_09_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_10_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_11_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_12_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_13_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_14_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_15_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_16_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_17_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_18_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_19_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_20_VAL", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_21_TXT", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_22_TXT", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_23_TXT", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_24_TXT", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_25_TXT", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_26_TXT", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_27_TXT", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_28_TXT", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_29_TXT", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_30_TXT", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_31_DATE", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_32_DATE", "STRING"),
        bigquery.SchemaField("CUSTM_STORE_MEASR_33_DATE", "STRING"),
        bigquery.SchemaField("RPLNT_OOS_STORE_CNT", "INTEGER"),
        bigquery.SchemaField("RPLNT_STORE_CNT", "INTEGER"),
        bigquery.SchemaField("STORE_ITEM_STTUS_CODE", "STRING"),
        bigquery.SchemaField("RET_TO_WHSE_UNITS_VAL", "STRING"),
        bigquery.SchemaField("RET_TO_WHSE_COST_VAL", "STRING"),
        bigquery.SchemaField("RET_TO_WHSE_RETL_VAL", "STRING"),
        bigquery.SchemaField("TOT_CNSMR_RET_RETL_VAL", "STRING"),
    ],
    skip_leading_rows=1,

    source_format=bigquery.SourceFormat.CSV,
    write_disposition="WRITE_TRUNCATE",
    time_partitioning = bigquery.TimePartitioning(
            type_= bigquery.TimePartitioningType.DAY,
            field = "SALES_DATE", 
        )
)
uri = "gs://{}/{}-*.csv".format(bucket_name, "POSDS_DAILY_FCT")

load_job = client.load_table_from_uri(
    uri, table_id, job_config=job_config
)  # Make an API request.

load_job.result()  # Waits for the job to complete.

destination_table = client.get_table(table_id)  # Make an API request.
print("Loaded {} rows.".format(destination_table.num_rows))